import Head from "next/head";

import Details from "@/Components/Details";
import Header from "@/Components/Header";
import Info from "@/Components/Info";
import Map from "@/Components/Map";
import Marquee from "@/Components/Marquee";
import Story from "@/Components/Story";

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Travis & Tanya Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/weddingIcon.ico" />
      </Head>
      <Header />
      <main className="w-full">
        <Info />
        <Story />
        <Details />
        <Map />
        <Marquee />
      </main>
    </>
  );
};

export default Home;
